[package]
name = "fallo-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0"
serde = "1"
serde_json = "1"
sled = "0"
tokio = "1"
toml = "0"
